# Generated by Django 5.2.10 on 2026-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[], default='Female', max_length=6),
            preserve_default=False,
        ),
    ]
