# Generated by Django 5.2.10 on 2026-05-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='none', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
